config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'pages#secret'
  get 'pages/secret'  => 'pages#secret'
	get '/login'     => 'sessions#new'
	post '/login'    => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  scope '/api' do
    resources :users
    resources :dialings
    get "/metrics_entry_exit/:id", to: "users#metrics_entry_exit"
    get "/metrics_late_employees", to: "dialings#metrics_late_employees"
    get "/metrics_overtime_employees", to: "dialings#metrics_overtime_employees"
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dialing.rb
class Dialing < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :dialings
  has_secure_password
  validates :email, presence: true, uniqueness: true

  def has_role?(role)
    self.role == role
  end
end

app/controllers/api_controller.rb
class ApiController < ActionController::API
  include Pundit
  helper_method :current_user
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  # Define the current_user method:
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize_login
    render_unauthorized('Access denied') if current_user.nil?
  end

  private

  def render_unauthorized(message)
    errors = { errors: { message: message } }
    render json: errors, status: :unauthorized
  end

  def user_not_authorized
    render json: { error: 'Unnecessary permissions' }, status: 403
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  helper_method :current_user

  # current_user method:
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize_login
    redirect_to login_path, alert: 'You must be logged in to access this page.' if current_user.nil?
  end
end

app/controllers/dialings_controller.rb
class DialingsController < ApiController
  before_action :authorize_login, only: [:index,:show, :create, :update, :metrics_late_employees, :metrics_overtime_employees ]

  def index
    @dialings = Dialing.all
    authorize [@dialings]
    render json: @dialings
  end

  def show
    @dialing = Dialing.find(params[:id])
    authorize [@dialing]
    render json: @dialing

  end

  def create
    @dialing = Dialing.new(dialing_params)
    authorize [@dialing]
    if @dialing.save
      render json: @dialing, status: :created
    else
      render json:  @dialing.errors, status: :bad_request
    end
  end

  def update
    @dialing = Dialing.find(params[:id])
    authorize [@dialing]
    if @dialing.update(dialing_params)
      render json: @dialing, status: :ok
    else
      render json:  @dialing.errors, status: :bad_request
    end
  end

  #reports
  def metrics_late_employees
    # http://localhost:3000/api/metrics_late_employees/?start_date=2019-10-01&end_date=2019-10-31
     @dialings = EmployeeQueries.new.late_employees(params[:start_date],params[:end_date])
     authorize [@dialings]
     render json: @dialings, status: :ok
  end

  def metrics_overtime_employees
    # http://localhost:3000/api/metrics_overtime_employees/?start_date=2019-10-01&end_date=2019-10-31
    @dialings = EmployeeQueries.new.overtime_employees(params[:start_date],params[:end_date])
    authorize [@dialings]
    render json: @dialings, status: :ok

  end

  rescue_from ActiveRecord::RecordNotFound do |e|
    render json: { message: e.message }, status: :not_found
  end

  private
  def dialing_params
    params.permit(:date, :category, :hour, :minute, :user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authorize_login, only: [:secret]
  def secret
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApiController

  def new
  end

  def create
    user = User.find_by(email: params[:email].downcase)
    # Verify user exists in db and run has_secure_password's .authenticate()
    if user && user.authenticate(params[:password])
    # if user && user.authenticate(params[:password])
      # Save the user.id in that user's session cookie:
      session[:user_id] = user.id.to_s
      render json: user, status: :ok
    else
      message = { error: "Invalid email or password" }
      render json: message, status: :unauthorized
    end
  end

  def destroy
    session.delete(:user_id)
    head :no_content
  end
end

app/controllers/users_controller.rb
class UsersController < ApiController
  before_action :authorize_login, only: [:index,:show, :create, :new, :metrics_entry_exit]
  def new
    @user = User.new
  end

  def index
    @users = User.all
    authorize [@users]
    render json: @users
  end

  def show
    @user = User.find(params[:id])
    authorize [@user]
    render json: @user
  end

  def create
    @user = User.new(user_params)
    authorize [@user]
    @user.email.downcase!

    if @user.save
      # If user saves in the db successfully:
      render json: @user, status: :created
    else
      render json:  @user.errors, status: :bad_request
    end
  end

  #Reports
  def metrics_entry_exit
    # http://localhost:3000/api/metrics_entry_exit/2/?start_date=2019-10-01&end_date=2019-12-31
     @dialings = EmployeeQueries.new.entry_exit(params[:id],params[:start_date],params[:end_date])
     @user=User.find(params[:id])
     authorize [@user]
     render json: @dialings, status: :ok
  end

  rescue_from ActiveRecord::RecordNotFound do |e|
    render json: { message: e.message }, status: :not_found
  end

private

  def user_params
    params.permit(:name,:email, :role, :password, :password_confirmation)

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dialings_helper.rb
module DialingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dialings/create.html.erb
<h1>Dialings#create</h1>
<p>Find me in app/views/dialings/create.html.erb</p>

app/views/dialings/index.html.erb
<h1>Dialings#index</h1>
<p>Find me in app/views/dialings/index.html.erb</p>

app/views/dialings/show.html.erb
<h1>Dialings#show</h1>
<p>Find me in app/views/dialings/show.html.erb</p>

app/views/dialings/update.html.erb
<h1>Dialings#update</h1>
<p>Find me in app/views/dialings/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmployeeTrack</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

      <% if current_user %>
        <!-- current_user will return true if a user is logged in -->
        <%= "Logged in as #{current_user.email}" %> | <%= link_to 'Home', root_path %> | <%= link_to 'Log Out', logout_path, method: :delete %>
      <% else %>
        <!-- not logged in -->
        <%= link_to 'Home', root_path %> | <%= link_to 'Log In', login_path %> or <%= link_to 'Sign Up', new_user_path %>
      <% end %>
      <hr>
    	<% if notice %>
      	<%= notice %>
	    <% end %>

	    <% if alert %>
      	<%= alert %>
	    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/secret.html.erb
<h1>Pages#secret</h1>
<p>Find me in app/views/pages/secret.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div>
    <%= f.submit "Sign up!" %>
  </div>
<% end %>